### ISSUE TITLE
Support for `osxarm64`?

### ISSUE THREAD

**Issue by darynwhite** [conda-forge/perl-app-cpanminus-feedstock#9]
### Comment:

Is there any chance there is the ability to add support for `arm` macOS systems?

**Comment by tdegeus** [comment]
There could be ;) Could you ask the migrator to open a PR : https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds ? We can take it from there

**Comment by darynwhite** [comment]
Thanks! I hadn't found that in the documentation yet, but it's bookmarked now!

**Comment by darynwhite** [comment]
Oh, this can close...
